# Generated by Django 4.1.3 on 2022-12-05 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('09239187-d154-422f-94fc-9fe29fdfb135'), primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.ManyToManyField(related_name='catergory', to='products.category')),
            ],
        ),
    ]
