# Generated by Django 4.1.3 on 2022-12-16 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4c73b5eb-30b2-428d-9599-17148182379f'), primary_key=True, serialize=False),
        ),
    ]
